[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
honor_noqa = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"
minversion = "6.2"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = """
    missing-function-docstring,
    missing-module-docstring,
    missing-class-docstring,
"""
